### ISSUE TITLE
세트로 스폰되어야 하는 아이템 룰

### ISSUE THREAD

**Issue by Hyesu** [Hyesu/MyProject#11]
#7 의 하위 이슈.
- [x] 세트로 스폰되어야 하는 아이템에 대하여  데이타 상으로 어떻게 알 수 있는지 문서화가 필요함
- [x] item_weapon 파싱
- [x] 무기 아이템 스폰시 탄약 아이템 함께 생성
- [x] 보너스로 생성해야 하는 아이템 룰 데이타에 맞춰서 작업

**Comment by geekor1021** [comment]
> #7 의 하위 이슈.
> 세트로 스폰되어야 하는 아이템에 대하여 데이타 상으로 어떻게 알 수 있는지 문서화가 필요함

위키 페이지에 해당 내용 추가 2.1.2. 아이템 스폰 하위 3.3.에 내용 추가
[위키링크](https://github.com/Hyesu/MyProject/wiki#toc-2-1-2)
참조해야할 값이 item의 SubType 값이여서 StrID나 ID로 바꿔야하는지?

**Comment by Hyesu** [comment]
@geekor1021 item_weapon.json의 Ammo 필드에는 item.json에 작성된 Ammo에 해당하는 아이템의 StrID를 작성해주세요!

**Comment by Hyesu** [comment]
68a3a19291958c2bfb30aabd69807b726c4b909b
작업 완료하였습니다.

**Comment by Hyesu** [comment]
보너스로 생성되어야 할 아이템에 대한 룰이 조금 더 있다고 해서 개발 진행 후 다시 닫을 예정

**Comment by Hyesu** [comment]
spawn_rule.json에 적힌 보너스 스폰 룰 데이타화 적용 완료
90aad6e94ca5d8aa3b8243ffb53d53b4b3ad744e
