### ISSUE TITLE
아이템 모델 데이타 반영

### ISSUE THREAD

**Issue by Hyesu** [Hyesu/MyProject#12]
- [x] 아이템 모델 데이타 입력
- [x] 데이타 기반으로 스폰되는 아이템 모델에 메쉬 반영

**Comment by Hyesu** [comment]
@geekor1021  모델 데이타 입력 부탁드립니다.

**Comment by geekor1021** [comment]
> @geekor1021 모델 데이타 입력 부탁드립니다.

SVN rev.8 item.json에 데이터 반영 했습니다.

**Comment by Hyesu** [comment]
b0561001cb3883d2ebc3997d908132db27a930a4
작업 완료!
