### ISSUE TITLE
아이템 스폰 룰 정리

### ISSUE THREAD

**Issue by Hyesu** [Hyesu/MyProject#2]
아이템 스폰을 위해 item.json, spawn.json의 프로퍼티가 각각 어떻게 사용되어야 하는지 정리가 필요함

**Comment by geekor1021** [comment]
[위키 페이지 - 아이템 스폰 룰](https://github.com/Hyesu/MyProject/wiki/PROJECT-SG#%EC%95%84%EC%9D%B4%ED%85%9C-%EC%8A%A4%ED%8F%B0) 작성완료

**Comment by Hyesu** [comment]
아이템별 weight를 계산하기 위한 데이타 테이블 참조법도 명세에 추가 부탁드립니다

**Comment by geekor1021** [comment]
[위키 페이지 - 아이템 스폰 룰](https://github.com/Hyesu/MyProject/wiki#%EC%95%84%EC%9D%B4%ED%85%9C-%EC%8A%A4%ED%8F%B0) 추가했습니당
