### ISSUE TITLE
아이템 스폰 기능

### ISSUE THREAD

**Issue by geekor1021** [Hyesu/MyProject#7]
- [x] 1. 스포너에 MinCount, MaxCount 지정할 수 있어야 함
- [x] <s>2. 세트로 나와야 하는 아이템이 있음</s>(하위 이슈 #11 에서 다루기로 함)
- [x] 3. 생성 확률 반영
- [x] 3-1. 변경된 데이타로 잘 스폰되는지 확인하기
- [x] 4. 스폰되는 아이템은 네비 메시 위에 나타나야 함
- [ ] 5. 스폰되는 아이템의 모델을 데이타로 정할 수 있도록 해야 함

**Comment by Hyesu** [comment]
레벨에 spawner 배치 후 사용 가능한 형태. 사용하면서 피드백  필요

**Comment by Hyesu** [comment]
- [ ] 스포너에 MinCount, MaxCount 지정할 수 있어야 함
- [ ] 세트로 나와야 하는 아이템이 있음
- [ ] 생성 확률 반영
- [ ] 스폰되는 아이템은 네비 메시 위에 나타나야 함
- [ ] 스폰되는 아이템의 모델을 데이타로 정할 수 있도록 해야 함

**Comment by Hyesu** [comment]
@geekor1021 
* Spawner 클래스를 레벨에 배치하여 사용할 수 있게 해두었음
* Spawner 클래스의 Detail을 통해 min, max 카운트 정할 수 있게 해두었음

**Comment by Hyesu** [comment]
@geekor1021  3번 항목 작업 중 spawner.json의 형식 변경이 필요한 부분이 있음
샘플 데이타 커밋하였으니 참고 부탁드립니다.
b49c404a1b5e6bcbf2089a30876ce36c19e07643

**Comment by geekor1021** [comment]
SVN 저장소로 데이터 이전작업 하였습니다. (spawner.json) svn rev.5

> @geekor1021 3번 항목 작업 중 spawner.json의 형식 변경이 필요한 부분이 있음
> 샘플 데이타 커밋하였으니 참고 부탁드립니다.
> [b49c404](https://github.com/Hyesu/MyProject/commit/b49c404a1b5e6bcbf2089a30876ce36c19e07643)

**Comment by Hyesu** [comment]
5번은 #12 일감에서 진행할 예정. 모든 서브 태스크 완료하여 일감 닫음
